// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7RqcbrVir3H7w5Hpu19MO151FTMmJlgo',
    appId: '1:889071847183:web:d48a53d4293819bf4c207a',
    messagingSenderId: '889071847183',
    projectId: 'payapp-23878',
    authDomain: 'payapp-23878.firebaseapp.com',
    databaseURL: 'https://payapp-23878-default-rtdb.firebaseio.com',
    storageBucket: 'payapp-23878.appspot.com',
    measurementId: 'G-YBQV9BKG2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkfMj6Ji7snfxKBgnpKWWefSIyqBw83VA',
    appId: '1:889071847183:android:ae2e5ccb05b9ee764c207a',
    messagingSenderId: '889071847183',
    projectId: 'payapp-23878',
    databaseURL: 'https://payapp-23878-default-rtdb.firebaseio.com',
    storageBucket: 'payapp-23878.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAteuQHZrr8ZC0a-oGbFAjHtO36xmGvc-8',
    appId: '1:889071847183:ios:b214e31245610a614c207a',
    messagingSenderId: '889071847183',
    projectId: 'payapp-23878',
    databaseURL: 'https://payapp-23878-default-rtdb.firebaseio.com',
    storageBucket: 'payapp-23878.appspot.com',
    iosBundleId: 'com.example.pay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAteuQHZrr8ZC0a-oGbFAjHtO36xmGvc-8',
    appId: '1:889071847183:ios:3608a85d024199084c207a',
    messagingSenderId: '889071847183',
    projectId: 'payapp-23878',
    databaseURL: 'https://payapp-23878-default-rtdb.firebaseio.com',
    storageBucket: 'payapp-23878.appspot.com',
    iosBundleId: 'com.example.pay.RunnerTests',
  );
}
